using System;
using System.Diagnostics;
using System.IO;
using Microsoft.CodeAnalysis;

namespace BlogEngine.Markdown
{
    [Generator]
    public class MarkdownGenerator : ISourceGenerator
    {
        public void Execute(GeneratorExecutionContext context)
        {
            foreach (var file in context.AdditionalFiles)
            {
                if (Path.GetExtension(file.Path).Equals(".md", StringComparison.OrdinalIgnoreCase))
                {
                    var markdown = file.GetText();

                    var htmlString = Markdig.Markdown.ToHtml(markdown.ToString());

                    context.AddSource($"Markdown_{Path.GetFileNameWithoutExtension(file.Path)}.g.cs", $@"// <auto-generated/>" + htmlString);                    
                }
            }
        }

        public void Initialize(GeneratorInitializationContext context)
        {

        }
    }
}
