name: Deploy to Github Pages

# Run workflow on every push to the master branch
on:
  push:
    branches: [ master ]

jobs:
  deploy-to-github-pages:
    # use ubuntu-latest image to run steps on
    runs-on: ubuntu-latest
    steps:
      # uses GitHub's checkout action to checkout code form the master branch
      - uses: actions/checkout@v4
      
      # sets up .NET 9 SDK
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
      
      # publishes Blazor project to the release-folder
      - name: Publish .NET Core Project
        run: dotnet publish src/mohdali.github.io/mohdali.github.io.csproj -c Release -o Prerender/output --nologo
      
      # Use NodeJS react-snap utitility to prerender static website
      - name: prerender Blazor client
        working-directory: Prerender
        run: |
          npx react-snap || true
          # Verify that index.html was created
          if [ ! -f "output/wwwroot/index.html" ]; then
            echo "Pre-rendering failed - no index.html generated"
            exit 1
          fi
          echo "Pre-rendering completed successfully"

      # Remove Blazor script tags from pre-rendered HTML files
      - name: Remove Blazor scripts
        working-directory: Prerender/output/wwwroot
        run: |
          find . -name "*.html" | while read htmlFile; do
              # Remove .NET 9 Blazor autostart script
              sed -i 's/<script src="_framework\/blazor.webassembly.js" autostart="false"><\/script>//g' $htmlFile
              # Remove any remaining Blazor-related scripts
              sed -i 's/<script>Blazor\.start.*<\/script>//g' $htmlFile
              # Remove dotnet.js references
              sed -i 's/<script src="_framework\/dotnet\.[^"]*\.js"[^>]*><\/script>//g' $htmlFile
          done

      # add .nojekyll file to tell GitHub pages to not treat this as a Jekyll project. (Allow files and folders starting with an underscore)
      - name: Add .nojekyll file
        run: touch Prerender/output/wwwroot/.nojekyll
        
      
      - name: Commit wwwroot to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: Prerender/output/wwwroot
        
      
